In [4]:
import numpy as np

In [23]:
n1= np.array((1,2,3,4))
n1

array([1, 2, 3, 4])

In [18]:
n2 = np.array(((4,5,6),(1,2,3)))
n2.shape

(2, 3)

In [19]:
n3 = np.array([[[1,2,3],
                [1,2,3]],
               
               [[4,5,6],
               [1,2,3]],
               
              [[7,8,9],
              [1,2,3]]])
n3.shape

(3, 2, 3)

In [25]:
n1.shape, n1.ndim, n1.dtype, n1.size, type(n1)

((4,), 1, dtype('int32'), 4, numpy.ndarray)

In [26]:
n2.shape, n2.ndim, n2.dtype, n2.size, type(n2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [27]:
n3.shape, n3.ndim, n3.dtype, n3.size, type(n3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [28]:
import pandas as pd

In [32]:
df = pd.DataFrame(n1)
df

,0
0,1
1,2
2,3
3,4


In [33]:
n_ones = np.ones(shape=(10,2))
n_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
n_zeros = np.zeros(shape=(7, 2, 3))
n_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
n_array = np.random.randint(0,101, size =(7,2))
n_array

array([[65, 65],
       [ 1, 48],
       [81, 86],
       [71, 69],
       [26, 27],
       [35, 38],
       [62,  8]])

In [46]:
n_random_float = np.random.random(size = (3, 5))
n_random_float

array([[0.74016644, 0.99689825, 0.77693529, 0.87865852, 0.81995454],
       [0.54621961, 0.7131771 , 0.0425252 , 0.42514733, 0.89361932],
       [0.67262666, 0.42844355, 0.19427239, 0.54017234, 0.88462713]])

In [56]:
np.random.seed(42)
n4 = np.random.randint(1,11, size = (4, 6))
n4


array([[ 7,  4,  8,  5,  7, 10],
       [ 3,  7,  8,  5,  4,  8],
       [ 8,  3,  6,  5,  2,  8],
       [ 6,  2,  5,  1, 10,  6]])

In [57]:
np.unique(n4)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])